steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/canini:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/canini:latest']
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - run
  - --location=europe-west1-b
  - --cluster=cluster
  - --filename=kubeconfig.yaml