---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canini
  namespace: default
  labels:
    app: canini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canini
  template:
    metadata:
      labels:
        app: canini
    spec:
      containers:
        - name: web
          image: gcr.io/canini-mascots-1/canini
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/canini
      volumes:
        - name: datasources
          configMap:
            name: datasources
---
apiVersion: v1
kind: Service
metadata:
  name: balancer
spec:
  selector:
    app: canini
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: default
  labels:
    app: canini
spec:
  scaleTargetRef:
    kind: Deployment
    name: canini
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
