---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canini-1
  namespace: default
  labels:
    app: canini-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canini-1
  template:
    metadata:
      labels:
        app: canini-1
    spec:
      containers:
        - name: canini
          image: gcr.io/weighty-flag-238618/canini:test
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/canini
      volumes:
        - name: datasources
          configMap:
            name: datasources
---
apiVersion: v1
kind: Service
metadata:
  name: canini-service
spec:
  selector:
    app: canini-1
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: canini-1-hpa
  namespace: default
  labels:
    app: canini-1
spec:
  scaleTargetRef:
    kind: Deployment
    name: canini-1
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
